### ISSUE TITLE
SDK retry panics after long times with same session

### ISSUE THREAD

**Issue by mega-alex** [oracle/oci-go-sdk#339]
After leaving the SDK running with a session for multiple days any API call will return this error

```
panicked while retrying operation. Panic was: interface conversion: interface {} is nil, not *http.ResponseStack: goroutine 1387537 [running]:
github.com/oracle/oci-go-sdk/v53/common.Retry.func1.1()
    /root/go/pkg/mod/github.com/oracle/oci-go-sdk/v53@v53.0.0/common/retry.go:873 +0x7b
panic({0x15af500, 0xc0007f3c20})
    /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/oracle/oci-go-sdk/v53/common.BaseClient.CallWithDetails({{0x1b4bd80, 0xc000a7eb10}, {0x1b4cce0, 0xc00111ce60}, 0x0, {0xc0002a95c0, 0x38}, {0xc000fc2e10, 0x2e}, {0x17e396b, ...}, ...}, ...)
    /root/go/pkg/mod/github.com/oracle/oci-go-sdk/v53@v53.0.0/common/client.go:591 +0x49b
github.com/oracle/oci-go-sdk/v53/common.BaseClient.Call(...)
    /root/go/pkg/mod/github.com/oracle/oci-go-sdk/v53@v53.0.0/common/client.go:559
github.com/oracle/oci-go-sdk/v53/containerengine.ContainerEngineClient.createCluster({{{0x1b4bd80, 0xc000a7eb10}, {0x1b4cce0, 0xc00111ce60}, 0x0, {0xc0002a95c0, 0x38}, {0xc000fc2e10, 0x2e}, {0x17e396b, ...}, ...}, ...}, ...)
    /root/go/pkg/mod/github.com/oracle/oci-go-sdk/v53@v53.0.0/containerengine/containerengine_client.go:193 +0x296
github.c
```
Also looks like the error string gets cut off there for some reason so the full stack trace isn't returned.

To reproduce this using SDK v53:
```go
configProvider := common.NewRawConfigurationProvider(
	tenancy, user, region, fingerprint, privateKey, privateKeyPassphrase,
)

client, err := containerengine.NewContainerEngineClientWithConfigurationProvider(configProvider)
if err != nil {
	return containerengine.ContainerEngineClient{}, err
}

// Wait here for a few days...

r, err := containerClient.CreateCluster(ctx, containerengine.CreateClusterRequest{
        CreateClusterDetails: input,
})
if err != nil {
	return nil, err // Here's the panic error
}


```

**Comment by mega-alex** [comment]
Actually after doing some more digging, the same error occurred in about 172 minutes today (pod uptime)

**Comment by ZiyaoQiao** [comment]
Hi @mega-alex we recently fixed this nil pointer issue. You can upgrade your go SDK version to v55.0.0+ and try again. Thanks for sharing this info!

**Comment by mega-alex** [comment]
Great, I'll upgrade and verify!

**Comment by ZiyaoQiao** [comment]
@mega-alex As we have resolved this issue and haven't heard back from you for a long time. I'm closing this issue. Feel free to reopen if you're having any issues. Thanks!
