### ISSUE TITLE
Dynamic block on oci_load_balancer_rule_set result on plugin crash

### ISSUE THREAD

**Issue by auriben** [oracle/oci-go-sdk#361]
I'm trying to implement the following code using nested dynamic blocks:

```
resource "oci_load_balancer_rule_set" "rule_set" {
  count = length(local.rule_sets_keys)

  load_balancer_id = oci_load_balancer_load_balancer.load_balancer.id
  name             = local.rule_sets_keys[count.index]

  dynamic "items" {
    iterator = rule
    for_each = local.rule_sets[local.rule_sets_keys[count.index]]

    content {
      action                          = rule.value.action
      allowed_methods                 = rule.value.allowed_methods
      are_invalid_characters_allowed  = rule.value.are_invalid_characters_allowed
      dynamic "conditions" {
        for_each = rule.value.action == "REDIRECT"  ? [1] : []
        content {
          attribute_name  = rule.value.conditions.attribute_name
          attribute_value = rule.value.conditions.attribute_value
          operator        = rule.value.conditions.operator
        }
      }
      description                     = rule.value.description
      header                          = rule.value.header
      http_large_header_size_in_kb    = rule.value.http_large_header_size_in_kb
      prefix                          = rule.value.prefix
      redirect_uri                    {
        path      = rule.value.redirect_uri.path
        host      = rule.value.redirect_uri.host
        port      = rule.value.redirect_uri.port
        protocol  = rule.value.redirect_uri.protocol
        query     = rule.value.redirect_uri.query
      }
      response_code                   = rule.value.response_code
      status_code                     = rule.value.status_code
      suffix                          = rule.value.suffix
      value                           = rule.value.value
    }
  }
}
```

but when I add the line
```
for_each = rule.value.action == "REDIRECT"  ? [1] : []
```
and action is different from REDIRECT I get the following error:

```
╷
│ Error: Plugin did not respond
│
│   with module.load_balancer.oci_load_balancer_backend.lb_backend[0],
│   on ../../../isd_common/terraform/modules/load_balancer_composite/load_balancer_composite.tf line 344, in resource "oci_load_balancer_backend" "lb_backend":
│  344: resource "oci_load_balancer_backend" "lb_backend" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.load_balancer.oci_load_balancer_rule_set.rule_set[0],
│   on ../../../isd_common/terraform/modules/load_balancer_composite/load_balancer_composite.tf line 362, in resource "oci_load_balancer_rule_set" "rule_set":
│  362: resource "oci_load_balancer_rule_set" "rule_set" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-oci_v4.76.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 342 [running]:
github.com/terraform-providers/terraform-provider-oci/internal/service/load_balancer.itemsHashCodeForSets({0x518c5e0, 0xc00233c180})
	github.com/terraform-providers/terraform-provider-oci/internal/service/load_balancer/load_balancer_rule_set_resource.go:1022 +0xb74
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x104da69, {0x518c5e0, 0xc00233c180})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/set.go:251 +0x2c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc001ad1540, {0x518c5e0, 0xc00233c180}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/set.go:231 +0x96
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readSet(0xc00200ade0, {0xc001faf480, 0x1, 0x1}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_config.go:284 +0x4f3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readField(0xc00200ade0, {0xc001faf480, 0x100ca74, 0xa9005b8}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_config.go:107 +0x54a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).ReadField(0xc00200ade0, {0xc001faf480, 0x1, 0x1})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_config.go:29 +0xc5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc001faf470, {0xc001faf480, 0x1, 0x1}, {0x5b61935, 0x6})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_multi.go:31 +0xb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc001fbc200, {0xc001faf480, 0x1, 0x1}, 0x1)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource_data.go:548 +0x16c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0x8d2a301, {0x5b603ed, 0xc00241f130}, 0xec, 0xcd)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource_data.go:524 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0x5, {0x5b603ed, 0x100c23e})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource_data.go:501 +0x88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffSet(0xc00241f5d0, {0x5b603ed, 0x5}, 0xc001784780, 0xc00241f5b8, {0x6355b88, 0xc001fbc200}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:1238 +0x82
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x5b61413, {0x5b603ed, 0x5}, 0xc001784780, 0xc001b56980, {0x6355b88, 0xc001fbc200}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:963 +0x225
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0017687e0, {0x6348d08, 0xc00229cdc0}, 0xc001caf650, 0xc00200a8d0, 0x0, {0x5b36800, 0xc001a782a0}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:522 +0x23e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x634f288, {0x6348d08, 0xc00229cdc0}, 0xc001caf650, 0x0, {0x5b36800, 0xc001a782a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:506 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc000124cf0, {0x6348d08, 0xc00229cdc0}, 0xc0030a1e50)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:693 +0x6cc
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc00052f680, {0x6348db0, 0xc00309ff50}, 0xc0030a1c20)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:315 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x58958e0, 0xc00052f680}, {0x6348db0, 0xc00309ff50}, 0xc00012cb40, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a5880, {0x6375650, 0xc00077c000}, 0xc002610c00, 0xc0018fc780, 0x8d3fce8, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0003a5880, {0x6375650, 0xc00077c000}, 0xc002610c00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-oci_v4.76.0 plugin crashed!
```

Is there any workaround to this, I have nested dynamic blocks in other resources like WAF and haven't faced this issue

Thanks

**Comment by jodoglevy** [comment]
@auriben it looks like you're using the OCI Terraform provider, not the OCI Go SDK itself. Can you open an issue in the OCI Terraform Provider Github (https://github.com/oracle/terraform-provider-oci) and close this one?

**Comment by jodoglevy** [comment]
Closing this, since I haven't heard back from you in 9 days
