### ISSUE TITLE
Error: panicked while retrying operation. Panic was: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dbhandiwadra** [oracle/oci-go-sdk#376]
Seeing this with terraform apply frequently 
Error: panicked while retrying operation. Panic was: runtime error: invalid memory address or nil pointer dereference
Stack: goroutine 483 [running]:
github.com/oracle/oci-go-sdk/v65/common.Retry.func1.1()
	github.com/oracle/oci-go-sdk/v65@v65.15.0/common/retry.go:813 +0x7b
panic({0x4948000, 0x87c6640})
	runtime/panic.go:1038 +0x215
github.com/oracle/oci-go-sdk/v65/common.Retry.func1()
	github.com/oracle/oci-go-sdk/v65@v65.15.0/common/retry.go:888 +0x556
created by github.com/oracle/oci-go-sdk/v65/common.Retry
	github.com/oracle/oci-go-sdk/v65@v65.15.0/common/retry.go:807 +0x267

**Comment by dbhandiwadra** [comment]
Didnt see with terraform version Terraform v1.2.6. 
 Terraform initialization
Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/oci...
- Finding latest version of hashicorp/null...
- Installing hashicorp/random v3.3.2...
- Installed hashicorp/random v3.3.2 (signed by HashiCorp)
- Installing hashicorp/oci v4.87.0...
- Installed hashicorp/oci v4.87.0 (signed by HashiCorp)
- Installing hashicorp/null v3.1.1...
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
